version: 0.2

phases:
  pre_build:
    commands:
      - pip install semgrep
      - echo "Listing source files:"
      - ls -al
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Starting Docker service..."
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo "Running SAST with Semgrep..."
      - semgrep --config=p/ci --error

      - echo Building Docker image...
      - docker build -t $ImageName -f ./Dockerfile .

      - echo "Running container for DAST scan..."
      - docker run -d -p 8080:8080 --name myapp $ImageName

      - echo "Running OWASP ZAP baseline scan..."
      - docker run -v $(pwd):/zap/wrk/:rw --network="host" -t owasp/zap2docker-stable \
          zap-baseline.py -t http://localhost:8080 -r zap_report.html -w zap_warnings.md
  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag $ImageName:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ImageName:latest
      - echo Pushing Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ImageName:latest
  
  artifacts:
    files:
      - zap_warnings.html
      - zap_warnings.md
