version: 0.2

phases:
  pre_build:
    commands:
      - pip install semgrep
      - semgrep --config=p/ci --error

  build:
    commands:
      - terraform init
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo "Running OWASP ZAP scan..."
      - docker run --rm -v $(pwd)/zap_output:/zap/wrk/:rw zaproxy/zap-stable zap-baseline.py -t http://$APP_PUBLIC_DNS -r zap_report.html -w zap_warnings.md

     

artifacts:
  files:
    - zap_output/zap_report.html
    - zap_output/zap_warnings.md