version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.6.3/terraform_1.6.3_linux_amd64.zip
      - unzip terraform_1.6.3_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
      - pip install semgrep
      - semgrep --config=p/ci --error

  build:
    commands:
      - terraform init
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
      - APP_PUBLIC_DNS=$(terraform output -raw app_dns)

  post_build:
    commands:
      - mkdir -p zap_output
      - chmod 777 zap_output
      - docker run --rm -v $(pwd)/zap_output:/zap/wrk/:rw zaproxy/zap-stable zap-baseline.py -t http://$APP_PUBLIC_DNS -r zap_report.html -w zap_warnings.md
      - terraform destroy -auto-approve
     

artifacts:
  files:
    - zap_output/zap_report.html
    - zap_output/zap_warnings.md